version: '3'
services:
  app:
    image: app
    container_name: app
    links:
      - mysql:container_mysql
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ./docker/conf/supervisor/conf.d:/etc/supervisor/conf.d
      - ./docker/conf/nginx:/etc/nginx
      - ./docker/conf/logs:/var/www/logs
      - ./server:/var/www/html/server
      - ./client:/var/www/html/client

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currencyshop