version: '3'
services:
#  angular:
#    image: dopsyng_angular
#    container_name: angular
#    ports:
#      - 4200:4200
#    volumes:
#      - ./client:/var/www/html

  php7:
    image: dopsyng_php7
    container_name: php7
    links:
      - mysql:container_mysql
    ports:
      - 80:80
      - 4200:4200
    volumes:
      - ./docker/conf/supervisor/conf.d:/etc/supervisor/conf.d
      - ./docker/conf/nginx:/etc/nginx
      - ./docker/conf/logs:/var/www/logs
      - ./server:/var/www/html/server
      - ./client:/var/www/html/client

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currencyshop